stages:
  - sync-code

sync-code:
  stage: sync-code
  only:
    - master
  script:
    - mkdir -p /root/codes && cd /root/codes
    - chmod 600 /root/.ssh/id_rsa
    - git clone ssh://git@gitlab.qiushaocloud.top:61023/qiushaocloud/clash-docker.git
    - cd clash-docker
    - sh push-remote-git-repos.sh
  tags:
    - qiushaocloud-runner
