stages:
  - sync-code

sync-code:
  stage: sync-code
  only:
    - master
  script:
    - cat .git/config
    - git branch -a
    - git checkout master
    - cat .git/config
    - git branch -a
    - sh push-remote-git-repos.sh
  tags:
    - qiushaocloud-runner
